name: app_acampamentos_hallel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.5.0
  package_info_plus: ^8.1.1
  flutter_native_splash: ^2.4.2
  url_launcher: ^6.3.1
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.14.1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  dio: ^5.7.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/logos/canaa/
  
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        style: italic
        weight: 700
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        style: italic 
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-LightItalic.ttf
        style: italic
        weight: 300
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        style: italic
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        style: italic
        weight: 600
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        style: italic
        weight: 100

