// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5nfCb8ZsDr-8WBdLUIpSq17OERIqPM4Y',
    appId: '1:238964277898:web:21ffd433f33e0c32ac2373',
    messagingSenderId: '238964277898',
    projectId: 'canaa-afb9f',
    authDomain: 'canaa-afb9f.firebaseapp.com',
    storageBucket: 'canaa-afb9f.appspot.com',
    measurementId: 'G-N2L5ZMV29N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpnZiRGDPY4dVfvkn8ULCf3NfNLrJEp8',
    appId: '1:238964277898:android:9ef5745096b082c9ac2373',
    messagingSenderId: '238964277898',
    projectId: 'canaa-afb9f',
    storageBucket: 'canaa-afb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHFzmEhNMPXWXRGUoXJISn05EZ7MnefI',
    appId: '1:238964277898:ios:492e42d78ad8798aac2373',
    messagingSenderId: '238964277898',
    projectId: 'canaa-afb9f',
    storageBucket: 'canaa-afb9f.appspot.com',
    iosBundleId: 'com.example.appAcampamentosHallel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClHFzmEhNMPXWXRGUoXJISn05EZ7MnefI',
    appId: '1:238964277898:ios:492e42d78ad8798aac2373',
    messagingSenderId: '238964277898',
    projectId: 'canaa-afb9f',
    storageBucket: 'canaa-afb9f.appspot.com',
    iosBundleId: 'com.example.appAcampamentosHallel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5nfCb8ZsDr-8WBdLUIpSq17OERIqPM4Y',
    appId: '1:238964277898:web:8d8ed9718e1f8c2eac2373',
    messagingSenderId: '238964277898',
    projectId: 'canaa-afb9f',
    authDomain: 'canaa-afb9f.firebaseapp.com',
    storageBucket: 'canaa-afb9f.appspot.com',
    measurementId: 'G-8YNE11WVW2',
  );
}
